### ISSUE TITLE
Infinite Loop Issue on Decoding Error in audio_mp3.cpp

### ISSUE THREAD

**Issue by alibukharai** [chmorgan/esp32-audio-player#5] opened 2023-05-22 06:08 UTC
**Description:**
I have been working with the audio component in the  project and have encountered an issue when an error occurs during the decoding of an MP3 file. Specifically, when any error happens during decoding, the program gets stuck in a continuous loop indefinitely. This behavior occurs in the decode_mp3 function, as referenced in this line: [audio_mp3.cpp#L139](https://github.com/chmorgan/esp-audio-player/blob/2221e2c848c9f073f9d6ab4fc6a5cd9b46de20c7/audio_mp3.cpp#L139).

**The crossponding error logs are attached below.**
![1](https://github.com/chmorgan/esp-audio-player/assets/60029742/ff777074-4324-4c05-981a-f39d4f41c9aa)

**Proposed solution:** 
To address this issue, I propose adding an event to the audio_player module. This event will allow proper handling of decoding errors and prevent the program from getting stuck in the loop. I have identified the relevant location to add the event in the audio_player.h file, as referenced in this line: [audio_player.h#L75](https://github.com/chmorgan/esp-audio-player/blob/2221e2c848c9f073f9d6ab4fc6a5cd9b46de20c7/include/audio_player.h#L75).

-  Add a new event type AUDIO_PLAYER_REQUEST_ERROR to the audio_player_event_type_t enumeration in audio_player.h.

> typedef enum {
>     // ...
>     AUDIO_PLAYER_REQUEST_ERROR, // New event type for handling decoding errors
>     // ...
> } audio_player_event_type_t;

**Comment by chmorgan** [comment] 2023-05-22 12:11
@alibukharai how are you able to reproduce this failure condition? Do you have a file that exhibits this behavior? I believe I had some files with some bad data in them and continuing to read got to a point where they worked, and should burn through the data in the file really quickly too, but I can see how several megabytes of bad data could take a long time to read and error through...

**Comment by alibukharai** [comment] 2023-05-23 02:49
> @alibukharai how are you able to reproduce this failure condition? Do you have a file that exhibits this behavior? I believe I had some files with some bad data in them and continuing to read got to a point where they worked, and should burn through the data in the file really quickly too, but I can see how several megabytes of bad data could take a long time to read and error through...

@chmorgan  Thank you for your response. The MP3 data is received through an HTTPS Text-to-Speech API. I store this data in a buffer and then pass both the buffer and its length to the [audio_player.cpp](https://github.com/chmorgan/esp-audio-player/blob/2221e2c848c9f073f9d6ab4fc6a5cd9b46de20c7/audio_player.cpp#L471) API to play the MP3. Below is the code snippet that handles the MP3 playback after the HTTPS finish event:

```
#define MAX_FILE_SIZE       (1*1024*1024)
    case HTTP_EVENT_ON_HEADER:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_HEADER");
        file_total_len = 0;
        break;
    case HTTP_EVENT_ON_DATA:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_DATA, len=%d", evt->data_len);
        if ((file_total_len + evt->data_len) < MAX_FILE_SIZE) {
            memcpy(audio_rx_buffer + file_total_len, (char *)evt->data, evt->data_len);
            file_total_len += evt->data_len;
        }
        break;
    case HTTP_EVENT_ON_FINISH:
        ESP_LOGI(TAG, "HTTP_EVENT_ON_FINISH:%d, %d K", file_total_len, file_total_len / 1024);
        audio_player_play(audio_rx_buffer, file_total_len); // Link: [https://github.com/chmorgan/esp-audio-player/blob/2221e2c848c9f073f9d6ab4fc6a5cd9b46de20c7/audio_player.cpp#L471]
        break;
```
The **challenge** is that reproducing this error is not straightforward. However, if such an error occurs, is there any way to provide guidance on how to handle it? The logs indicate a status error of -8 in [mp3dec.h](https://github.com/chmorgan/libhelix-mp3/blob/f4430799e70a4fff44513e71bd4459411802b819/pub/mp3dec.h#L100).

**Comment by chmorgan** [comment] 2023-06-12 22:24
@alibukharai well -8 looks like an internal data field/format error. Today we don't do a good job of indicating we are skipping due to errors, that could be something you could use to decide to abort playback entirely, vs. continuing for hundreds of ms to try to play the data file.

**Comment by chmorgan** [comment] 2023-06-12 22:24
I'd be open to suggestions for api/error reporting changes but keep in mind they could break existing users.

**Comment by chmorgan** [comment] 2023-12-13 13:23
@alibukharai can you retest with the latest changes on main? It looks like this issue may have been addressed.

**Comment by chmorgan** [comment] 2024-06-19 00:26
Closing as I think the issue was resolved with some fixes that were contributed.

**Closed as completed by chmorgan** 2024-06-19 00:26 UTC
